# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_name', models.CharField(blank=True, max_length=1024)),
                ('home_page', models.URLField(blank=True)),
                ('family_name', models.CharField(max_length=1024)),
                ('full_name', models.CharField(max_length=1024)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('given_name', models.CharField(blank=True, max_length=1024)),
                ('party', models.CharField(blank=True, max_length=512)),
                ('twitter', models.URLField(blank=True)),
            ],
        ),
    ]
