# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MPs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
