# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MPs', '0002_auto_20160405_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 5, 0, 56, 58, 6816, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 5, 0, 57, 4, 812646, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
