sudo: required
language: python
services:
  - docker
# cd into the api project
before_install:
  - make api
script:
  - make test-api
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" https://gcr.io
  - docker tag hansard_api gcr.io/hansard-1012/hansard_api:$(git rev-parse HEAD)
  - docker push gcr.io/hansard-1012/hansard_api:$(git rev-parse HEAD)
