language: python
python:
  - "3.4"
# cd into the api project
before_install: cd api
install: pip install -r requirements.txt
# change from /api to /api/api
before_script: cd api
script: python manage.py test
