db:
  image: postgres:9.6
api:
  build: ./api
  command: python api/manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  volumes:
    - ./api:/app
  links:
    - db
# client:
#   build: ./client
#   command: ember server
#  links:
#    - api
