# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('constituency_type', models.CharField(max_length=1024)),
                ('started_date', models.DateField()),
                ('ended_date', models.DateField(blank=True)),
                ('gss_code', models.CharField(max_length=512)),
                ('os_name', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
