# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='ended_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
