# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constituencies', '0002_auto_20160406_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='name',
            field=models.CharField(default='tim', max_length=1024),
            preserve_default=False,
        ),
    ]
